### PR TITLE
Added e-paper UI folder

### PR DESCRIPTION
**Pull request by petulla28**

### CODE REVIEW

**Comment by himanshujaidka** [comment]
sorry, for the delay, actually I am busy in my college exams

**Comment by petulla28** [comment]
> sorry, for the delay, actually I am busy in my college exams

Np, same here :)

**Comment by himanshujaidka** [comment]
pls, add a link to this on index.html, user is not able to see the e-paper option

**Comment by petulla28** [comment]
done! sorry for the delay.

**Pull request merged**
